# Generated by Django 5.0.7 on 2024-07-18 16:55

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='state',
            new_name='done',
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='item',
            name='due',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b6283f26-22ec-4846-8b7e-69b535f699cd'), unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
