# Generated by Django 5.0.7 on 2024-07-18 16:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_state_item_done_item_created_item_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('d82301fc-d483-410f-a281-0a6c3aac8c80'), unique=True),
        ),
    ]
