# Generated by Django 5.0.7 on 2024-07-18 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_created_alter_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('e5e3d6a6-a9c6-4e05-95b9-41579fa4623d'), editable=False, unique=True),
        ),
    ]
