# Generated by Django 5.0.7 on 2024-07-18 17:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('b0c89c40-bd56-42ec-b555-b9756bf0c2d3'), editable=False, unique=True),
        ),
    ]
